[project]
name = "memtools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bigtree>=0.23.1",
    "numpy>=2.2.2",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
]

[dependency-groups]
dev = [
    "basedpyright>=1.26.0",
    "pytest>=8.3.4",
    "syrupy>=4.8.1",
]
